
import Head from 'next/head';
import { fetchOneEvent} from '@/services/events';
import Form from '@/components/ui/form';

export interface DataEvent {
    id: number;
    title: string;
    short_description: string;
    content: string;
    category: string;
    location: string;
    created_by: string;
    createdAt: string,
  }

export default async function Edit({params:{id}}:{params:{id: string}}) {
    const data = await fetchOneEvent(Number(id))
  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="mt-28">
        <div className="container mx-auto  text-black">
          <div className="max-w-md mx-auto pb-12">
            <div className="bg-white p-8 rounded-lg shadow-lg shadow-gray-800">
              <h2 className="text-center text-black text-2xl font-bold mb-6">Event editing</h2>
              <Form data={data}/>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
