
import React from 'react';
import Head from 'next/head';
import { useState } from 'react';
import LoginForm from '@/components/ui/login';

export interface LoginFormData {
  email: string;
  password: string;
}
interface ApiResponse {
  status: number;
  message: string;
}


const Login = () => {
  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="mt-20">
        <div className="flex justify-center items-center pt-16">
          <div className="w-full max-w-md py-12">
            <div className="bg-white p-5 rounded-lg shadow-lg shadow-gray-800">
                <h2 className="text-2xl font-bold mb-6 text-center text-black">Log in form</h2>
              <LoginForm/>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;