
import Head from 'next/head';
import SignUpForm from '@/components/ui/signup';


export interface RegisterFormData {
  name: string;
  email: string;
  password: string;
}

export default function Register() {

  return (
    <>
      <Head>
        <title>Event Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="flex justify-center items-center pt-16">
        <div className="w-full max-w-md py-12">
          <div className="bg-white p-5 rounded-lg shadow-lg shadow-gray-800">
            <h2 className="text-2xl font-bold mb-6 text-center text-black">Sign up form</h2>
            <SignUpForm/>
          </div>
        </div>
      </div>
    </>
  );
}
